ambassador:
  enabled: true
  singleNamespace: false
certManager:
  enabled: false
controllerId: ''
crd:
  create: true
createResources: false
credentials:
  gcs:
    gcsCredentialFileName: gcloud-application-credentials.json
  s3:
    s3AccessKeyIDName: awsAccessKeyID
    s3SecretAccessKeyName: awsSecretAccessKey
defaultUserID: ''
engine:
  grpc:
    port: 5001
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/engine
    tag: 1.1.0
  logMessagesExternally: false
  port: 8000
  prometheus:
    path: /prometheus
  serviceAccount:
    name: default
  user: 8888
executor:
  defaultRequestLoggerEndpointPrefix: http://default-broker.
  enabled: true
  grpc:
    port: 5001
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/seldon-core-executor
    tag: 1.1.0
  port: 8000
  prometheus:
    path: /prometheus
  serviceAccount:
    name: default
  user: 8888
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: seldonio/seldon-core-operator
  tag: 1.1.0
istio:
  enabled: false
  gateway: istio-system/seldon-gateway
  tlsMode: ''
kubeflow: false
manager:
  cpuLimit: 500m
  cpuRequest: 100m
  memoryLimit: 300Mi
  memoryRequest: 200Mi
predictiveUnit:
  defaultEnvSecretRefName: ''
  port: 9000
predictor_servers:
  MLFLOW_SERVER:
    grpc:
      defaultImageVersion: '0.4'
      image: seldonio/mlflowserver_grpc
    rest:
      defaultImageVersion: '0.4'
      image: seldonio/mlflowserver_rest
  SKLEARN_SERVER:
    grpc:
      defaultImageVersion: '0.2'
      image: seldonio/sklearnserver_grpc
    rest:
      defaultImageVersion: '0.2'
      image: seldonio/sklearnserver_rest
  TENSORFLOW_SERVER:
    grpc:
      defaultImageVersion: '0.7'
      image: seldonio/tfserving-proxy_grpc
    rest:
      defaultImageVersion: '0.7'
      image: seldonio/tfserving-proxy_rest
    tensorflow: true
    tfImage: tensorflow/serving:2.1.0
  XGBOOST_SERVER:
    grpc:
      defaultImageVersion: '0.3'
      image: seldonio/xgboostserver_grpc
    rest:
      defaultImageVersion: '0.3'
      image: seldonio/xgboostserver_rest
rbac:
  configmap:
    create: false
  create: false
serviceAccount:
  create: false
  name: seldon-manager
singleNamespace: false
storageInitializer:
  cpuLimit: '1'
  cpuRequest: 100m
  image: gcr.io/kfserving/storage-initializer:0.2.2
  memoryLimit: 1Gi
  memoryRequest: 100Mi
usageMetrics:
  enabled: false
webhook:
  port: 443
